apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity: 
    storage: 1Gi
  accessModes: # ReadWriteOnce, ReadOnlyMany, ReadWriteMany (Many의 기준은 노드)
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain # pvc 삭제시 정책 (Retain, Delete, )
  hostPath: # volume type
    path: /tmp/mongodb
