apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce # ReadWriteOnce, ReadOnlyMany, ReadWriteMany (Many의 기준은 노드)
  # 1. default sc 사용 : 명시하지 않으면 됨, pv 생성
  # 2. sc 미사용, 사전 프로비저닝된 pv 사용
  #storageClassName: ""
  # 3. sc 지정, pv 생성
  storageClassName: fast
