apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  type: ClusterIP # NodePort, LoadBalancer
  sessionAffinity: None # ClientIP
  externalTrafficPolicy: Cluster # Local
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: kubia
