apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  # label 추가
  labels:
    creation_method: manual
    env: prod
spec:
  # node label 지정
  nodeSelector:
    gpu: "true"
  containers:
    - image: luksa/kubia
      name: kubia
      ports:
        - containerPort: 8080
          protocol: TCP
